name: "aqua"
repository: github.com/argonsecurity/trivy-plugin-aqua-dev
version: dev
usage: trivy aqua <srcPath>
description: A Trivy plugin that sends results to Aqua.
platforms:
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/argonsecurity/trivy-plugin-aqua-dev/releases/download/dev/trivy_manual_linux_amd64.tar.gz
    bin: ./aqua
